//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rushMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_Template
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Form_Template()
        {
            this.Form_Assignment = new HashSet<Form_Assignment>();
        }
    
        public int Form_ID { get; set; }
        public string Form_Desc { get; set; }
        public Nullable<int> Question_ID { get; set; }
        public Nullable<int> Assignment_ID { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Assignment Assignment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Form_Assignment> Form_Assignment { get; set; }
        public virtual Question Question { get; set; }
    }
}
