//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rushMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_Assignment
    {
        public int Form_Assingment_ID { get; set; }
        public int User_ID { get; set; }
        public int Form_ID { get; set; }
        public int Question_ID { get; set; }
        public int Patient_ID { get; set; }
        public string Answer { get; set; }
        public byte[] Date_Time { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
    
        public virtual Form_Template Form_Template { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Question Question { get; set; }
        public virtual User User { get; set; }
    }
}
