//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rushMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medical_History
    {
        public int Medical_ID { get; set; }
        public int Patient_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> DATE_TIME { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
